# Generated by Django 2.1.5 on 2020-06-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Things',
            new_name='Thing',
        ),
    ]
